### ISSUE TITLE
Start Class Is Empty in Teacher

### ISSUE THREAD

**Issue by atif-vsbizz** [fakhruddin-vsbizz/arabic-moallema-refactored-v2.0#27]
Start Class Is Empty in Teacher Dashboard at: teacher/class/

@somesh2001

**Comment by somesh2001** [comment]
![Screenshot (397)](https://user-images.githubusercontent.com/56119880/224647633-30dec8b1-d123-4b6b-b200-81b4e0eb37a7.png)
No it's not empty , it is working and functional ,just the dynamic url need to be set in the student report, once i work on the student report  part i will do this.(like if we navigate from student report to live class it dosen't show anything because for that currently there is no route)
