### ISSUE TITLE
Edit teacher and Edit student

### ISSUE THREAD

**Issue by somesh2001** [fakhruddin-vsbizz/arabic-moallema-refactored-v2.0#43]
- When we are editing student or teacher in the teacher/student profile page, currently we are not editing the email. because if we update the email the user cannot log in to the application.

- This needs to be discussed with @fakhruddin-vsbizz 

pages - 

- http://localhost:3000/admin/students/studentprofile/ishwaranjana142@gmail.com
- http://localhost:3000/admin/teachers/teacherprofile/somesh.anjana@avantika.edu.in

**Comment by fakhruddin-vsbizz** [comment]
What we can do @atif-vsbizz since email is a credential-severe field, we will be isolating that too and then build a two-stage verified update process.

- A file is popped up where a new email is entered.
- A mail with a random UUID is sent for verifying the proper email.
- Inside the popup, we will open the verification code textbox.
- Once verified, we will update the email field with the authentication table.

@atif-vsbizz you can look into the UI part as to how to implement in the UI side.

**Comment by fakhruddin-vsbizz** [comment]
Flow for the same:
- Another section called "Change Email Address"
- Insert new email address.
- Changes email inside Authentication.
- Emails previous client title "Arabic Moallema: Your access are shifted to <NEW EMAIL ADDRESS>"
- Emails new client with same email as new user with same password in email.

**Comment by somesh2001** [comment]
Done, An email notification will be sent to the previous email also notified to the new email.
